language: c
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install ruby rake bison git gperf
before_script:
    - git clone https://github.com/ksss/mruby-spec.git ../mruby-spec
    - cd ../mruby-spec
script:
    - make MRUBY_CONFIG="../../mruby-signal/.travis-build_config.rb" TESTS="core/{signal,exception/{interrupt,signal_exception}_spec.rb}"
notifications:
  email: false
