language: c
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install ruby rake bison git gperf
before_script:
  - git clone --depth 1 https://github.com/ksss/mruby-spec.git ../mruby-spec
script:
  - cd ../mruby-spec
  - mkdir -p unsupported/signal
  - echo "Signal.list doesn't contain other signals than the known list" > unsupported/signal/list.txt
  - make MRUBY_CONFIG="../../mruby-signal/.travis-spec-build_config.rb" TESTS="core/signal core/exception/interrupt_spec.rb core/exception/signal_exception_spec.rb"
  - cd mruby
  - make test MRUBY_CONFIG="../../mruby-signal/.travis-test-build_config.rb"
notifications:
  email: false
